### ISSUE TITLE
Can not see the "Loading more" and "Refresh..."

### ISSUE THREAD

**Issue by realcarlos** [pedia/pdrpulm#1]
Just could see the list .

in iOS , the list could be pulled down and pull up 

but in Android ,the list could not be pulled

**Comment by pedia** [comment]
I published a new version. Please check the new versioned demo.

**Comment by carlosbdw** [comment]
Thank you for updating it .
Could we have a sample of placing the 'Pull down to refresh' text to the header of the list ? and moving with the pull down gesture?

**Comment by pedia** [comment]
Maybe later
