### ISSUE TITLE
Hey, my friend! I get a problem! 

### ISSUE THREAD

**Issue by YugeCse** [pedia/pdrpulm#2]
I opened "pdrpulm.dart" file, I saw some to-do tags!
`    if (_mode == _PullIndicatorMode.armed && _dragOffset > 0.0) {
      // TODO: Show Refresh Indicator
    }

    if (_mode == _PullIndicatorMode.armed && _dragOffset < 0.0) {
      // TODO: Show LoadMore Indicator
    }
`
What should I do that if I want to add my indicator for the refresh-contorl? 
And, I find the control can't work well when it's  refreshing state or loadmore state .

**Comment by pedia** [comment]
The TODOs are no problem.

Add a refresh control is not simple. You should use RefreshIndicator instead.
