### ISSUE TITLE
receive an exception when using lib

### ISSUE THREAD

**Issue by xuehu54321** [pedia/pdrpulm#3]
I/flutter (21693): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (21693): The following _CompileTimeError was thrown while notifying listeners for AnimationController:
I/flutter (21693): 'package:pdrpulm/pdrpulm.dart': error: line 39 pos 12:
I/flutter (21693): file:///Users/ning/.pub-cache/hosted/pub.dartlang.org/pdrpulm-1.0.2/lib/pdrpulm.dart:39:12: Error: A
I/flutter (21693): value of type '() → dart.core::bool' can't be assigned to a variable of type 'dart.core::bool'.
I/flutter (21693): Try changing the type of the left hand side, or casting the right hand side to 'dart.core::bool'.
I/flutter (21693):     assert(() {
I/flutter (21693):            ^
I/flutter (21693):     assert(() {
I/flutter (21693):            ^
I/flutter (21693): When the exception was thrown, this was the stack:
I/flutter (21693): #0      _ScrollIndicatorState._handleScrollNotification (package:pdrpulm/pdrpulm.dart:78:13)
I/flutter (21693): #1      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:127:27)
I/flutter (21693): #2      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:47:20)
I/flutter (21693): #3      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:36:18)
I/flutter (21693): #4      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3278:39)
I/flutter (21693): #5      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:61:12)
I/flutter (21693): #6      ScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:95:96)
I/flutter (21693): #7      ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:597:14)
I/flutter (21693): #8      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:218:9)
I/flutter (21693): #9      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:85:18)
I/flutter (21693): #10     BallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/scroll_activity.dart:523:21)
I/flutter (21693): #11     BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:510:10)
I/flutter (21693): #12     _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:109:19)
I/flutter (21693): #13     AnimationController._tick (package:flutter/src/animation/animation_controller.dart:546:5)
I/flutter (21693): #14     Ticker._tick (package:flutter/src/scheduler/ticker.dart:228:5)
I/flutter (21693): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (21693): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
I/flutter (21693): #17     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
I/flutter (21693): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
I/flutter (21693): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
I/flutter (21693): #20     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (21693): #21     _beginFrame (dart:ui/hooks.dart:105:3)

**Comment by pedia** [comment]
fixed
